### ISSUE TITLE
@pulumi/eks acquired from NPM doesn't have index.js

### ISSUE THREAD

**Issue by swgillespie** [pulumi/eks#1]
Not sure what the deal is here, but the `@pulumi/eks` package I got from NPM doesn't have an `index.js` in it.
![screen shot 2018-08-23 at 9 46 50 am](https://user-images.githubusercontent.com/1871912/44539611-79f41500-a6b9-11e8-8683-edcaf422b6ce.png)

Without an `index.js`, I can't `import * as eks from "@pulumi/eks"`. I can `import * as eks from "@pulumi/eks/cluster"`, though.

**Comment by pgavlin** [comment]
This should be fixed if you use the "dev" label in your package.json
