### ISSUE TITLE
Expose method to set userdata for creating EKS worker nodes

### ISSUE THREAD

**Issue by eshamay** [pulumi/eks#14]
My use case requires that the EKS worker nodes install some custom drivers and packages (e.g. nfs-utils, flexvolume drivers, etc.) any time a new host is started and joins the cluster.

Currently this is accomplished by explicitly using CloudFormation templates, but would be simpler via pulumi/eks.

My specific use is in python.

**Comment by pgavlin** [comment]
Fixed by #15.
