### ISSUE TITLE
Will you be working on Go implementation of this module too?

### ISSUE THREAD

**Issue by houqp** [pulumi/eks#16]
Hi,

Just curious, is the eks module going to stay in JS or are you planning to roll out implementation in other languages too?

Thanks,

**Comment by houqp** [comment]
That's good to know. We will stick to Node for now then :) Are you going to transpile from node to other languages?

**Comment by lukehoban** [comment]
> Are you going to transpile from node to other languages?

Yes - we are looking into a few different paths we may go for enabling cross-language access to libraries like this one without maintaining independent ports in each language.

**Comment by pgavlin** [comment]
That's a good question.

As of now, we expect that we will do the translation by hand. We are not currently aware of a technology to do Node -> * transpilation in a satisfactory fashion.

**Comment by houqp** [comment]
Thanks for the quick replies. I will close this issue for now. Looking forward to the Go version :)
